### Normalize or standardize numerical features using manual calculations instead of built-in functions, ensuring robust handling of outliers and skewed distributions.

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [40]:
df = pd.read_csv("heart.csv")
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [25]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [26]:
df.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [27]:
df.count()

age         303
sex         303
cp          303
trestbps    303
chol        303
fbs         303
restecg     303
thalach     303
exang       303
oldpeak     303
slope       303
ca          303
thal        303
target      303
dtype: int64

In [28]:
df.shape

(303, 14)

In [29]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [31]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000
mean,54.366337,0.683168,0.966997,131.623762,246.264026,0.148515,0.528053,149.646865,0.326733,1.039604,1.399340,0.729373,2.313531,0.544554
std,9.082101,0.466011,1.032052,17.538143,51.830751,0.356198,0.525860,22.905161,0.469794,1.161075,0.616226,1.022606,0.612277,0.498835
min,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,47.500000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.500000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.000000,1.000000,1.000000,130.000000,240.000000,0.000000,1.000000,153.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,274.500000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [32]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [33]:
numerical_columns = [
    "age",
    "trestbps",
    "chol",
    "thalach",
    "oldpeak"
]

print(numerical_columns)

['age', 'trestbps', 'chol', 'thalach', 'oldpeak']

In [34]:
#manually identify outliers
for column in numerical_columns:

    values = sorted(df[column].tolist())

    n = len(values)

    q1_index = int(0.25 * (n - 1))
    q3_index = int(0.75 * (n - 1))

    q1 = values[q1_index]
    q3 = values[q3_index]

    iqr = q3 - q1

    lower_limit = q1 - 1.5 * iqr
    upper_limit = q3 + 1.5 * iqr

    outlier_count = 0

    for value in values:
        if value < lower_limit or value > upper_limit:
            outlier_count += 1

    print("\nColumn:", column)
    print("Q1:", q1)
    print("Q3:", q3)
    print("IQR:", iqr)
    print("Lower Limit:", lower_limit)
    print("Upper Limit:", upper_limit)
    print("Outliers:", outlier_count)

Column: age
Q1: 47
Q3: 61
IQR: 14
Lower Limit: 26.0
Upper Limit: 82.0
Outliers: 0

Column: trestbps
Q1: 120
Q3: 140
IQR: 20
Lower Limit: 90.0
Upper Limit: 170.0
Outliers: 9

Column: chol
Q1: 211
Q3: 274
IQR: 63
Lower Limit: 116.5
Upper Limit: 368.5
Outliers: 5

Column: thalach
Q1: 133
Q3: 166
IQR: 33
Lower Limit: 83.5
Upper Limit: 215.5
Outliers: 1

Column: oldpeak
Q1: 0.0
Q3: 1.6
IQR: 1.6
Lower Limit: -2.4000000000000004
Upper Limit: 4.0
Outliers: 5

In [35]:
for column in numerical_columns:

    values = sorted(df[column].tolist())

    n = len(values)

    q1_index = int(0.25 * (n - 1))
    q3_index = int(0.75 * (n - 1))

    q1 = values[q1_index]
    q3 = values[q3_index]

    iqr = q3 - q1

    lower_limit = q1 - 1.5 * iqr
    upper_limit = q3 + 1.5 * iqr

    outlier_count = 0

    for value in values:
        if value < lower_limit or value > upper_limit:
            outlier_count += 1

    print("\nColumn:", column)
    print("Q1:", q1)
    print("Q3:", q3)
    print("IQR:", iqr)
    print("Lower Limit:", lower_limit)
    print("Upper Limit:", upper_limit)
    print("Outliers:", outlier_count)

Column: age
Q1: 47
Q3: 61
IQR: 14
Lower Limit: 26.0
Upper Limit: 82.0
Outliers: 0

Column: trestbps
Q1: 120
Q3: 140
IQR: 20
Lower Limit: 90.0
Upper Limit: 170.0
Outliers: 9

Column: chol
Q1: 211
Q3: 274
IQR: 63
Lower Limit: 116.5
Upper Limit: 368.5
Outliers: 5

Column: thalach
Q1: 133
Q3: 166
IQR: 33
Lower Limit: 83.5
Upper Limit: 215.5
Outliers: 1

Column: oldpeak
Q1: 0.0
Q3: 1.6
IQR: 1.6
Lower Limit: -2.4000000000000004
Upper Limit: 4.0
Outliers: 5

In [36]:
#mean and standard division
df_clean = df.copy()

# Convert numerical columns to float
for column in numerical_columns:
    df_clean[column] = df_clean[column].astype(float)


for column in numerical_columns:

    values = sorted(df_clean[column].tolist())

    n = len(values)

    q1_index = int(0.25 * (n - 1))
    q3_index = int(0.75 * (n - 1))

    q1 = values[q1_index]
    q3 = values[q3_index]

    iqr = q3 - q1

    lower_limit = q1 - 1.5 * iqr
    upper_limit = q3 + 1.5 * iqr

    for index in df_clean.index:

        value = df_clean.loc[index, column]

        if value < lower_limit:
            df_clean.loc[index, column] = lower_limit

        elif value > upper_limit:
            df_clean.loc[index, column] = upper_limit


print("Outliers handled successfully.")

Outliers handled successfully.

In [37]:
for column in numerical_columns:

    values = df_clean[column].tolist()

    total = 0

    for value in values:
        total = total + value

    mean = total / len(values)

    squared_sum = 0

    for value in values:
        squared_sum = squared_sum + (value - mean) ** 2

    variance = squared_sum / len(values)

    std = variance ** 0.5

    print("\n", column)
    print("Mean:", mean)
    print("Standard Deviation:", std)

 age
Mean: 54.366336633663366
Standard Deviation: 9.067101638577872

 trestbps
Mean: 131.2805280528053
Standard Deviation: 16.554854822770533

 chol
Mean: 245.1138613861386
Standard Deviation: 47.420467437113956

 thalach
Mean: 149.6881188118812
Standard Deviation: 22.736311460687027

 oldpeak
Mean: 1.0244224422442245
Standard Deviation: 1.1082934789142889

In [38]:
df_standardized = df_clean.copy()

for column in numerical_columns:

    values = df_clean[column].tolist()

    total = 0

    for value in values:
        total += value

    mean = total / len(values)

    squared_sum = 0

    for value in values:
        squared_sum += (value - mean) ** 2

    variance = squared_sum / len(values)

    std = variance ** 0.5

    if std != 0:

        for index in df_standardized.index:

            value = df_standardized.loc[index, column]

            df_standardized.loc[index, column] = (
                value - mean
            ) / std

print("Manual standardization completed.")

Manual standardization completed.

In [39]:
print("Original Data:")
display(df[numerical_columns].head())

print("\nStandardized Data:")
display(df_standardized[numerical_columns].head())

Original Data:

   age  trestbps  chol  thalach  oldpeak
0   63       145   233      150      2.3
1   37       130   250      187      3.5
2   41       130   204      172      1.4
3   56       120   236      178      0.8
4   57       120   354      163      0.6

Standardized Data:

        age  trestbps      chol   thalach   oldpeak
0  0.952197  0.828728 -0.255456  0.013717  1.150938
1 -1.915313 -0.077351  0.103039  1.641070  2.233684
2 -1.474158 -0.077351 -0.867007  0.981332  0.338879
3  0.180175 -0.681403 -0.192193  1.245228 -0.202494
4  0.290464 -0.681403  2.296184  0.585490 -0.382951